### ISSUE TITLE
Inference Code

### ISSUE THREAD

**Issue by ahmadmustafaanis** [mbanani/lgssl#3]
Is there a way to load the model and perform inference inside the code like 
```python
model = load_lgssl()

data = my_data[0] # single example
results = model(data)
```

**Comment by mbanani** [comment]
Hi @ahmadmustafaanis, 

we're in the process of adding torch hub functionality to our code base which should make this easier. This should happen in the next few weeks. 

For now, you need to follow the following steps after pulling the last commit which simplified the `get_model` function's input. 
1. Download the pretrained checkpoint that you want from here [here] (https://www.dropbox.com/sh/me6nyiewlux1yh8/AAAPrD2G0_q_ZwExsVOS_jHQa?dl=0) and put it in `data/checkpoints`. For example, if you are interested in the language-guided simclr model, you would download `lgsimclr.ckpt`. 
2. Run the following code:

```python
import torch
from lgssl.evaluation.utils import get_model

model = get_model("lgssl_checkpoints", "lgsimclr")   # the second variable is the name of the checkpoint

fake_img = torch.rand(1, 3, 224, 224).cuda()
fake_feat = model(fake_img)
```

Let me know if this works for you. I will update this once we get the torch hub loading up and running.

**Comment by ahmadmustafaanis** [comment]
This is great, it is working fine, if there is any way I can contribute to this repo as a beginner, with PyTorch hub or something other that is relatively simple and in your backlogs, do let me know. I'd love to contribute.

**Comment by mbanani** [comment]
Sorry for the delay. We have added the hunconf functionality and you can get any checkpoints using the following code snippet, just replace lgsimclr with whichever checkpoint you want to use. The list of available checkpoints can be seen on dropbox or by looking at [hubconf.py](https://github.com/mbanani/lgssl/blob/main/hubconf.py).


```python
import torch
model = torch.hub.load("mbanani/lgssl", "lgsimclr")
```
